config/routes.rb
Health::Application.routes.draw do
  root :to => "home#index"

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, :path => "user", :path_names => {:sign_in => "login", :sign_out => "logout", :sign_up => "signup"}

  scope "client" do
    get '(:platform)/recent', :to => "software_packages#recent"
    get '(:platform)' , :to => "software_packages#index"
  end


  resources :notifications do
    collection do
      get :from_date
    end
  end

  scope "/measurements" do
    [:temperatures, :cardiograms, :bloodpressures, :glucoses, :oxygens, :weights].each do |res|
      resources res, :controller => "measurements",
                :measurement_name => res,
                :as => "measurements_#{res}"
    end
  end

  resources :patients do
    collection do
      get 'account/:account_type/(:account_code)', :action => :account, :as => :account
      post :register
      post :add_account
    end
    member do
      get :enroll
      get :unlist
    end

    resources :notifications
    [:temperatures, :cardiograms, :bloodpressures, :glucoses].each do |res|
      resources res, :measurement_name => res,
                :controller => :measurements,
                :path => 'measurements/'+res.to_s,
                :as => "measurements_#{res}"
    end
    [:temperature_thresholds, :cardiogram_thresholds, :bloodpressure_thresholds, :glucose_thresholds].each do |res|
      resources res, :threshold_name => res,
                :controller => :measurement_thresholds,
                :path => 'measurement_thresholds/'+res.to_s,
                :as => "#{res}"
    end

    match 'measurements/last' => 'measurements#last'

  end

  controller :home, :action => 'show', :via => :get do
    match '/', :id => 'index'
    match '/contacts', :id => 'contacts'
    match '/about', :id => 'about'
    match '/privacy', :id => 'privacy'
    match '/terms', :id => 'terms'
  end

  resources :medical_device_lists, only: [:index, :create, :show, :update, :destroy]

  # API v2
  namespace :api_v2, path: 'api/v2' do
    scope '(:locale)', locale: /en|ru/ do
      devise_for :doctors
      devise_for :patients

      # Patients namespace
      namespace :patient do
        namespace :measurements do
          resources :bloodpressures, only: [:index, :create]
          resources :cardiograms, only: [:index, :create]
          resources :glucoses, only: [:index, :create]
          resources :oxygens, only: [:index, :create]
          resources :temperatures, only: [:index, :create]
          resources :weights, only: [:index, :create]
        end
      end

      # Doctors namespace
      namespace :doctor do
        resources :patients, only: [:index] do
          namespace :measurements do
            resources :bloodpressures, only: [:index, :create]
            resources :cardiograms, only: [:index, :create]
            resources :glucoses, only: [:index, :create]
            resources :oxygens, only: [:index, :create]
            resources :temperatures, only: [:index, :create]
            resources :weights, only: [:index, :create]
          end
        end
      end
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!, :except => :show

  def show
    render :template => "home/#{params[:id]}"
  end


  def index
    user = User.find_by_id(current_user)

    if user.is_patient?
      render :patient
    elsif user.is_doctor?
      redirect_to patients_path
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.haml
.patient_content
  %h1 About
  %p
    Global aim of this project is improving quality of medical service,
    minimizing costs of primary diagnosis of the patient and creating comfortable informational environment
    for accumulating history of medical measurements (e.g. body temperature, blood pressure, glucose, pulse,
    cardiogram and others) and providing simple and secure way to exchange this data between patient, doctor
    and other medical information systems.
  %p
    We use latest technologies of telemedicine and mobile medicine.

app/views/home/about.ru.html.haml
.patient_content
  %h1 О Проекте
  %p
    Глобальной целью данного проекта явялется улучшение качества мединцинского обслуживания,
    минимизация затрат на первичную диагностику пациента и создание удобной информационной среды для накопления истории
    медицинских измерений (температура, давление, содержание сахара в крови, пульс, кардиограмма и другие) и
    удобного обмена этими данными между врачем, пациентом и другими медицинскими информационными системами.
  %p
    Мы используем самые современные технические средства, технологии телемедицины и мобильной медицины.

app/views/home/contacts.html.haml
.patient_content
  %h1 Contacts
  %p
  %p

app/views/home/contacts.ru.html.haml
.patient_content
  %h1 Контактная информация
  %p
  %p

app/views/home/patient.html.haml
.patient_content
  %h1= t(".title")
  %div{:style => "text-align:left;margin-left:20px"}
    %ul
      %li= link_to t(".cardio"), measurements_cardiograms_path
      %li= link_to t(".bloodpressure"), measurements_bloodpressures_path
      %li= link_to t(".temperature"), measurements_temperatures_path
      %li= link_to t(".glucose"), measurements_glucoses_path
      %li= link_to t(".oxygen"), measurements_oxygens_path
      %li= link_to t(".weight"), measurements_weights_path

app/views/home/privacy.html.haml
.patient_content
  %h1 Privacy
  %p

app/views/home/privacy.ru.html.haml
.patient_content
  %h1 Приватность
  %p